name: "CI/CD"

on:
  push:
    branches: [ "playground" ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 720
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -Dlicense.skip -DskipTests && mvn test --fae
    - name: Run Application tests
      if: always()
      run: cd application && mvn test -Dlicense.skip --fae
